name: Funny Minseol Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
    - cron: "0 11 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show message
        run: echo "웃긴민설 자동화 테스트 성공"
